name: QYSTUDIOのSSLCheck

on: 
  push:
    branches: 
      - master
  schedule:
    - cron: '0 21 * * *' 

jobs:
  CheckSSL:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10'
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install & Build
      run: |
        npm i
        git clone https://github.com/qystudio0/CheckSSL --depth=2
        npm run build
        cd CheckSSL
        chmod +x checker.sh
        ./checker.sh qystudio.ltd status.qystudio.ltd qystudio.ml ssl.qystudio.ltd
        cp -rf ./output/ct.json ../public/ct.json
        echo "ssl.qystudio.ltd" > ../public/CNAME
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./public
